### PR TITLE
Arm build fix

### LINKED ISSUE #20: Support additional architectures (arm64)
It would be nice to support multi-architectures. When the container does not support the current architecture, the following error is produced and the pod will not run:
exec /manager: exec format error

### PR DESCRIPTION
**Pull request by jodevsa**
Fixes #20 

--------------------------
Hi @Matthew-Beckett,

I noticed that you have implemented the changes to support ARM builds. Currently there is a problem with pushing the images if the PR was opened by someone else other than me. I think it is mostly regarding permissions of pushing an image to github packages.

I'll open a PR for now so that we can work together in getting this implemented and merged :) 

Thanks a lot for helping!

### CODE REVIEW

**Comment by jodevsa** [comment]
Hi @Matthew-Beckett,

The current process is ugly so I'm fine with that 😃 

I wonder if you have any recommendations about automating releasing a yaml file. The reason why I added that release process is because it was useful to have a file generated on each PR so that I can quickly manually test it on a k8s cluster

**Comment by Matthew-Beckett** [comment]
I have made some more changes, but I cannot push to this branch, do you want to review and pull in: https://github.com/Matthew-Beckett/wireguard-operator/tree/feature/arm-build-fix?

**Comment by jodevsa** [comment]
Does building work on your branch? if that is the case I'll just close this one. Sorry for the mess :D

**Comment by jodevsa** [comment]
seems like it works. I'll close this one

**Pull request closed without merging**
