### PR TITLE
pass resources to deployment

### PR DESCRIPTION
**Pull request by winston0410**
For addressing #181

### CODE REVIEW

**Comment by jodevsa** [comment]
Hi @winston0410, thanks! You'll need to also run `make generate` and `make manifests` to update the crd yaml to include the new spec attributes. 


https://sdk.operatorframework.io/docs/cli/operator-sdk_generate/

**Comment by winston0410** [comment]
> Hi @winston0410, thanks! You'll need to also run `make generate` and `make manifests` to update the crd yaml to include the new spec attributes.
> 
> https://sdk.operatorframework.io/docs/cli/operator-sdk_generate/

Oh right totally missed the CRD generation bit, thank you for pointing me to the commands.

**Review by jodevsa — APPROVED** [review]
LGTM

**Comment by jodevsa** [comment]
btw, the project uses `semantic-release` to automate generating releases. You'll need to use semantic commit messages https://www.conventionalcommits.org/en/v1.0.0/ so that the automation tool releases a new version.


For example, you can squad and merge this PR with something like:

`feat: pass resources to deployment'

The `feat` part tells semantic-release that this is a new feature that doesn't have any breaking changes. so it will do a minor version bump 2.1.0 to 2.1.1 I think. I'm not really into the details of it but you can read more here: https://github.com/semantic-release/semantic-release

**Comment by winston0410** [comment]
> btw, the project uses `semantic-release` to automate generating releases. You'll need to use semantic commit messages https://www.conventionalcommits.org/en/v1.0.0/ so that the automation tool releases a new version.
> 
> For example, you can squash and merge this PR with something like:
> 
> `feat: pass resources to deployment'
> 
> The `feat` part tells semantic-release that this is a new feature that doesn't have any breaking changes. so it will do a minor version bump 2.1.0 to 2.1.1 I think. I'm not really into the details of it but you can read more here: https://github.com/semantic-release/semantic-release

Sure no problem, never used semantic-release so didn't realize it is the magic keyword that trigger the release. I guess I will bring out something like commitizen for my commit in this repo from now on

**Pull request merged**
