### PR TITLE
feat: add golangci-lint

### PR DESCRIPTION
**Pull request by uhthomas**
golangci-lint runs many analysers, including staticcheck, which prevent correctness issues and catch bugs.

https://golangci-lint.run/

Fixes: #160

### CODE REVIEW

**Comment by uhthomas** [comment]
Sort of blocked by #164

**Comment by uhthomas** [comment]
@jodevsa Would it be possible to merge this soon? Now? It looks like a lot of changes are being made and it would be great to prevent potential issues!

**Comment by winston0410** [comment]
Hey @uhthomas I am willing to take on this with you. Checked the PR and it looks good, do you mind resolving the conflict, so we can merge this?

**Pull request merged**
